# Project information
site_name: 'Web Security and Exploitation'
site_description: 'Web Security and Exploitation Resources for the PET Computer Sciece Club'
site_author: 'Kevin Dai et al.'
site_url: 'https://petcsclub.github.io/Hacking'

# Repository
repo_name: 'petcsclub/Hacking'
repo_url: 'https://github.com/petcsclub/Hacking'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Kevin Dai'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
  language: 'en'
  logo:
    icon: 'public'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/petcsclub'
  search:
    language: 'en'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true